# Generated by Django 3.2.4 on 2021-08-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210823_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Makaleye Fotoğraf Ekleyin'),
        ),
    ]
